spring:
  application:
    name: DnDManagementSystem
  #  thymeleaf:
  #    check-template-location: true
  #    cache: false
  #    prefix: file:./src/main/resources/templates/
  #server:
  #  port: 8081
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dndManagementSystem?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  spring:
    autoconfigure:
      exclude=org:
        springframework:
          boot:
            autoconfigure:
              security:
                SecurityAutoConfiguration:
dnd5eapi:
  api:
    url: "https://www.dnd5eapi.co/api"

campaigns:
  api:
    baseUrl: "http://localhost:8081"